Add support for BigInt
treeverse/delta-go pull request #3
Opened 2023-11-27 11:41 UTC by Jonathan-Rosenberg

For some reason `BigInt` is supported by the Delta Lake spec, yet this package didn't support it...

2023-11-27 12:14 UTC, johnnyaug commented on record.go
> +	v, err := checkPrimitiveField[*types.BigIntType](p, fieldName, "long")
```suggestion
	v, err := checkPrimitiveField[*types.LongType](p, fieldName, "long")
```

2023-11-27 20:49 UTC, nopcoder requested changes
Could you provide more details about the modification in the code where the "bigint" type, initially mapped to the Go type LongType, has now been altered to use a different type named BigInt? This new type appears to be a specific implementation of LongType, primarily differing in its designation as "bigint". In reviewing the Delta protocol specification (https://github.com/delta-io/delta/blob/master/PROTOCOL.md#primitive-types), I noticed that the 'long' type corresponds to "int64" as per the author's implementation. Furthermore, the specification mentions a decimal type resembling a big integer, which seems to be unimplemented in the current context. Could you clarify these aspects?

2023-11-28 10:08 UTC, Jonathan-Rosenberg commented
@nopcoder I've updated the description. Tell me if it makes sense

2023-11-28 10:17 UTC, Jonathan-Rosenberg commented
This fix will be handled differently in #2

2023-11-28 10:17 UTC, closed without merging